#PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cpu


##Introduction to tensors

###Creating tensors

In [2]:
#scalars
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#matrix
matrix=torch.tensor([[1,2],
                    [5,6]])
matrix

tensor([[1, 2],
        [5, 6]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
#tensor
tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
tensor.ndim

3

In [12]:
tensor.shape

torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
tensor[0][2][1]

tensor(8)

###Random Tensors

In [15]:
#creating a random tensor
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1333, 0.6598, 0.4923, 0.3493],
        [0.2138, 0.9572, 0.8956, 0.4090],
        [0.5884, 0.5900, 0.8154, 0.0732]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor=torch.rand(1,3,5)
random_tensor

tensor([[[6.2731e-01, 9.8134e-01, 8.6019e-01, 3.6878e-01, 6.5777e-01],
         [9.9887e-02, 5.4364e-01, 5.7563e-01, 1.3834e-01, 5.8185e-01],
         [7.7553e-01, 5.5790e-05, 8.0038e-01, 1.5214e-01, 5.5320e-01]]])

In [18]:
random_tensor.ndim,random_tensor.shape

(3, torch.Size([1, 3, 5]))

In [19]:
zero=torch.zeros(4,2,9)
zero

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [20]:
zero.dtype

torch.float32

In [21]:
ones=torch.ones(6,9)
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
#creating a tensor with range
range_tensor=torch.arange(start=0,end=1000,step=15)
range_tensor

tensor([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180, 195,
        210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405,
        420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570, 585, 600, 615,
        630, 645, 660, 675, 690, 705, 720, 735, 750, 765, 780, 795, 810, 825,
        840, 855, 870, 885, 900, 915, 930, 945, 960, 975, 990])

In [24]:
range_tensor.shape

torch.Size([67])

In [25]:
#to create tensors with similar shape to another tensor
zeros_like=torch.zeros_like(input=range_tensor)
print(zeros_like)
zeros_like.shape

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


torch.Size([67])

###Tensor Datatypes

In [26]:
float_16_tensor=torch.tensor([[9,8,7],
                              [6,7,8]],
                             dtype=torch.float16)
float_16_tensor

tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float16)

In [27]:
float_16_tensor.dtype

torch.float16

In [28]:
torch.tensor([1,2,3],
             dtype=None, #to edit the datatype of the tensor
             device=None, #what device the tensor is on
             requires_grad=False) #whether or not to track the gradients

tensor([1, 2, 3])

In [29]:
float_64_tensor=float_16_tensor.type(torch.float64)
float_64_tensor

tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float64)

In [30]:
float_16_tensor*float_64_tensor #dtype promotion

tensor([[81., 64., 49.],
        [36., 49., 64.]], dtype=torch.float64)

In [31]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
float_16_tensor*int_32_tensor #dtype promotion

tensor([[27., 48., 63.],
        [18., 42., 72.]], dtype=torch.float16)

###Getting attributes from tensor

1. Getting datatype- use tensor.dtype
2. Getting shape   - use tensor.shape
3. Getting device  - use tensor.device

In [33]:
tensor_random=torch.rand(3,4,7)
tensor_random

tensor([[[0.7081, 0.2257, 0.4782, 0.7588, 0.2166, 0.0379, 0.4216],
         [0.1724, 0.1919, 0.6122, 0.1661, 0.5477, 0.8608, 0.0567],
         [0.1872, 0.6961, 0.8047, 0.2439, 0.5574, 0.7343, 0.8985],
         [0.3325, 0.7032, 0.3419, 0.6095, 0.6519, 0.6841, 0.3027]],

        [[0.4387, 0.7312, 0.3807, 0.8565, 0.7226, 0.0643, 0.5323],
         [0.0068, 0.9184, 0.8504, 0.4877, 0.4452, 0.7374, 0.7788],
         [0.5096, 0.7737, 0.3895, 0.0985, 0.2572, 0.0519, 0.5229],
         [0.1738, 0.7948, 0.9515, 0.6573, 0.0748, 0.0956, 0.8461]],

        [[0.1248, 0.3378, 0.0596, 0.5036, 0.3680, 0.7130, 0.3236],
         [0.4219, 0.7329, 0.9434, 0.5368, 0.7314, 0.5714, 0.5715],
         [0.4877, 0.5460, 0.4803, 0.5839, 0.3884, 0.5394, 0.4538],
         [0.9102, 0.9782, 0.6511, 0.6872, 0.2777, 0.8051, 0.7630]]])

In [34]:
tensor_random.shape,tensor_random.dtype,tensor_random.device

(torch.Size([3, 4, 7]), torch.float32, device(type='cpu'))

In [35]:
int_32_tensor.shape,int_32_tensor.dtype,int_32_tensor.device

(torch.Size([3]), torch.int32, device(type='cpu'))

###Tensor Operations

1. Addition
2. Subtraction
3. Multiplication
4. division
5. Matrix Multiplication

In [36]:
#addition
tensor_random+10
#do the same operation for all values

tensor([[[10.7081, 10.2257, 10.4782, 10.7588, 10.2166, 10.0379, 10.4216],
         [10.1724, 10.1919, 10.6122, 10.1661, 10.5477, 10.8608, 10.0567],
         [10.1872, 10.6961, 10.8047, 10.2439, 10.5574, 10.7343, 10.8985],
         [10.3325, 10.7032, 10.3419, 10.6095, 10.6519, 10.6841, 10.3027]],

        [[10.4387, 10.7312, 10.3807, 10.8565, 10.7226, 10.0643, 10.5323],
         [10.0068, 10.9184, 10.8504, 10.4877, 10.4452, 10.7374, 10.7788],
         [10.5096, 10.7737, 10.3895, 10.0985, 10.2572, 10.0519, 10.5229],
         [10.1738, 10.7948, 10.9515, 10.6573, 10.0748, 10.0956, 10.8461]],

        [[10.1248, 10.3378, 10.0596, 10.5036, 10.3680, 10.7130, 10.3236],
         [10.4219, 10.7329, 10.9434, 10.5368, 10.7314, 10.5714, 10.5715],
         [10.4877, 10.5460, 10.4803, 10.5839, 10.3884, 10.5394, 10.4538],
         [10.9102, 10.9782, 10.6511, 10.6872, 10.2777, 10.8051, 10.7630]]])

In [37]:
#multiplication
tensor_random*21

tensor([[[14.8698,  4.7405, 10.0420, 15.9357,  4.5493,  0.7962,  8.8543],
         [ 3.6200,  4.0293, 12.8566,  3.4875, 11.5013, 18.0778,  1.1914],
         [ 3.9321, 14.6178, 16.8978,  5.1211, 11.7053, 15.4199, 18.8677],
         [ 6.9833, 14.7681,  7.1798, 12.7990, 13.6906, 14.3668,  6.3562]],

        [[ 9.2124, 15.3558,  7.9945, 17.9860, 15.1754,  1.3503, 11.1787],
         [ 0.1433, 19.2867, 17.8575, 10.2410,  9.3486, 15.4860, 16.3556],
         [10.7020, 16.2481,  8.1789,  2.0687,  5.4002,  1.0909, 10.9803],
         [ 3.6508, 16.6914, 19.9810, 13.8035,  1.5706,  2.0084, 17.7677]],

        [[ 2.6211,  7.0948,  1.2515, 10.5752,  7.7285, 14.9732,  6.7962],
         [ 8.8609, 15.3914, 19.8124, 11.2726, 15.3590, 12.0003, 12.0010],
         [10.2421, 11.4665, 10.0865, 12.2615,  8.1556, 11.3277,  9.5290],
         [19.1147, 20.5420, 13.6733, 14.4317,  5.8312, 16.9078, 16.0232]]])

In [38]:
#subtraction
tensor_random-9

tensor([[[-8.2919, -8.7743, -8.5218, -8.2412, -8.7834, -8.9621, -8.5784],
         [-8.8276, -8.8081, -8.3878, -8.8339, -8.4523, -8.1392, -8.9433],
         [-8.8128, -8.3039, -8.1953, -8.7561, -8.4426, -8.2657, -8.1015],
         [-8.6675, -8.2968, -8.6581, -8.3905, -8.3481, -8.3159, -8.6973]],

        [[-8.5613, -8.2688, -8.6193, -8.1435, -8.2774, -8.9357, -8.4677],
         [-8.9932, -8.0816, -8.1496, -8.5123, -8.5548, -8.2626, -8.2212],
         [-8.4904, -8.2263, -8.6105, -8.9015, -8.7428, -8.9481, -8.4771],
         [-8.8262, -8.2052, -8.0485, -8.3427, -8.9252, -8.9044, -8.1539]],

        [[-8.8752, -8.6622, -8.9404, -8.4964, -8.6320, -8.2870, -8.6764],
         [-8.5781, -8.2671, -8.0566, -8.4632, -8.2686, -8.4286, -8.4285],
         [-8.5123, -8.4540, -8.5197, -8.4161, -8.6116, -8.4606, -8.5462],
         [-8.0898, -8.0218, -8.3489, -8.3128, -8.7223, -8.1949, -8.2370]]])

In [39]:
#functions
tensor=torch.mul(tensor_random,10)
print(f"Multiplying 10 : {tensor}")
tensor=torch.add(tensor_random,10)
print(f"Adding 10 : {tensor}")

Multiplying 10 : tensor([[[7.0808, 2.2574, 4.7819, 7.5885, 2.1663, 0.3791, 4.2163],
         [1.7238, 1.9187, 6.1222, 1.6607, 5.4768, 8.6085, 0.5674],
         [1.8724, 6.9609, 8.0466, 2.4386, 5.5740, 7.3428, 8.9846],
         [3.3254, 7.0324, 3.4190, 6.0948, 6.5194, 6.8413, 3.0267]],

        [[4.3868, 7.3123, 3.8069, 8.5647, 7.2264, 0.6430, 5.3232],
         [0.0682, 9.1841, 8.5036, 4.8767, 4.4517, 7.3743, 7.7884],
         [5.0962, 7.7372, 3.8947, 0.9851, 2.5715, 0.5195, 5.2287],
         [1.7385, 7.9483, 9.5148, 6.5731, 0.7479, 0.9564, 8.4608]],

        [[1.2481, 3.3785, 0.5960, 5.0358, 3.6802, 7.1301, 3.2363],
         [4.2195, 7.3293, 9.4345, 5.3679, 7.3138, 5.7144, 5.7148],
         [4.8772, 5.4602, 4.8031, 5.8388, 3.8836, 5.3941, 4.5376],
         [9.1022, 9.7819, 6.5111, 6.8722, 2.7768, 8.0513, 7.6301]]])
Adding 10 : tensor([[[10.7081, 10.2257, 10.4782, 10.7588, 10.2166, 10.0379, 10.4216],
         [10.1724, 10.1919, 10.6122, 10.1661, 10.5477, 10.8608, 10.0567],
         [10.

####Matrix Multiplication

1. Element wise multiplication
2. Multiplying with another matrix i.e dot product

In [40]:
#Element wise multiplication
print(int_32_tensor)
print(float_16_tensor)
element_mul=int_32_tensor*float_16_tensor
element_mul

tensor([3, 6, 9], dtype=torch.int32)
tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float16)


tensor([[27., 48., 63.],
        [18., 42., 72.]], dtype=torch.float16)

In [41]:
#matrix multiplicationt
tensor_1=torch.rand(4,5)
tensor_2=torch.rand(5,4)

mat_mul=torch.matmul(tensor_1,tensor_2)
mat_mul_short=torch.mm(tensor_1,tensor_2)#alias of matmul
mat_mul_inv=torch.mm(tensor_2,tensor_1)

mat_mul,mat_mul_short,mat_mul_inv

(tensor([[0.9646, 1.5628, 1.8040, 2.1598],
         [0.5392, 0.7482, 0.8898, 1.1502],
         [0.6967, 0.9212, 0.6549, 1.2693],
         [1.2404, 1.8272, 1.7055, 2.4629]]),
 tensor([[0.9646, 1.5628, 1.8040, 2.1598],
         [0.5392, 0.7482, 0.8898, 1.1502],
         [0.6967, 0.9212, 0.6549, 1.2693],
         [1.2404, 1.8272, 1.7055, 2.4629]]),
 tensor([[0.6470, 1.3593, 0.7157, 1.0027, 1.3283],
         [0.5576, 0.6439, 1.0444, 0.6536, 1.0113],
         [0.5370, 1.0272, 0.7764, 0.8657, 1.2048],
         [0.8384, 1.4372, 1.1553, 1.1332, 1.6098],
         [0.9697, 1.5996, 1.1999, 1.1318, 1.6300]]))

In [42]:
#the most common error in matrix multiplication : shape error
tensor_mul_1=torch.rand(3,4)
tensor_mul_2=torch.rand(2,3)

mat_mul_tensor=torch.matmul(tensor_mul_1,tensor_mul_2) #the inner dimensions must match
mat_mul_tensor

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 2x3)

In [43]:
#using transpose
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
tensor_A.T,tensor_B.T

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [44]:
tensor_C=torch.mm(tensor_A,tensor_B.T)
tensor_C

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Tensor Aggregation
1. Mean
2. Max
3. Min
4. Sum

In [45]:
x=torch.arange(0,100,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [46]:
#min
torch.min(x)

tensor(0)

In [47]:
#max
torch.max(x)

tensor(95)

In [48]:
#mean
torch.mean(x)
#output shd match the tensor dtype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

torch.mean doesnt work with int types.

In [49]:
torch.mean(x.type(torch.float32))

tensor(47.5000)

In [50]:
#sum
torch.sum(x)

tensor(950)

###Positional min and max

In [51]:
#positional minimum
x.argmin()

tensor(0)

In [52]:
#positional maximum
x.argmax()

tensor(19)

In [53]:
x[0],x[19]

(tensor(0), tensor(95))

###Reshaping,stacking,squeezing and unsqueezing tensors

* Reshaping- reshaping the input tensor to a different tensor
* View     - return a view of an input tensor of certain shape but keep memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze  - remove dimensions from tensor
* Unsqueeze- add dimension to a tensor
* Permute  - return a view of the input with the dimensions permuted in a certain way

In [54]:
x=torch.arange(1.,50.,5)
x

tensor([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46.])

In [55]:
x.shape

torch.Size([10])

In [56]:
#reshaping
x_reshaped=x.reshape(5,2) #reshape has to be compatible with original shape
x_reshaped

tensor([[ 1.,  6.],
        [11., 16.],
        [21., 26.],
        [31., 36.],
        [41., 46.]])

In [57]:
#change the view
z=x.view(10,1)
z,z.shape

(tensor([[ 1.],
         [ 6.],
         [11.],
         [16.],
         [21.],
         [26.],
         [31.],
         [36.],
         [41.],
         [46.]]),
 torch.Size([10, 1]))

In [58]:
#changing z changes x because a view share the original tensor's memory
#like shallow copy ig
z[7,:]=52
z,x

(tensor([[ 1.],
         [ 6.],
         [11.],
         [16.],
         [21.],
         [26.],
         [31.],
         [52.],
         [41.],
         [46.]]),
 tensor([ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.]))

In [59]:
#stacking
x_stacked=torch.stack([x,x],dim=0)
x_stacked

tensor([[ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.],
        [ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.]])

In [60]:
x_stacked=torch.stack([x,x],dim=1)
x_stacked

tensor([[ 1.,  1.],
        [ 6.,  6.],
        [11., 11.],
        [16., 16.],
        [21., 21.],
        [26., 26.],
        [31., 31.],
        [52., 52.],
        [41., 41.],
        [46., 46.]])

In [61]:
#squeezing
x=torch.arange(0.,10.)
x_reshaped=x.reshape(1,10)

x_squeezed=torch.squeeze(x_reshaped,dim=0)

In [62]:
x_reshaped.shape,x_squeezed.shape

(torch.Size([1, 10]), torch.Size([10]))

In [63]:
#unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [64]:
#permuting-returns a view with dimensions rearranged
x=torch.ones(size=(4,2,7))
x


tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])

In [65]:
x_permuted=x.permute(2,0,1) #shifts axis 0->2, 1->0, 2->1


In [66]:
x_permuted.shape,x.shape

(torch.Size([7, 4, 2]), torch.Size([4, 2, 7]))

###Indexing in PyTorch

In [67]:
x=torch.arange(1.,10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [68]:
#indexing on the tensor
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [69]:
x[0][0],x[0,0]

(tensor([1., 2., 3.]), tensor([1., 2., 3.]))

In [70]:
x[0,1,1]

tensor(5.)

In [71]:
x[0,2,1]

tensor(8.)

In [72]:
#using : to select all values of a particular dimension
x[:,2]

tensor([[7., 8., 9.]])

In [73]:
x[:,2,:]

tensor([[7., 8., 9.]])

In [74]:
x[0,:,:]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

##PyTorch and NumPy

PyTorch has functionality to interact with NumPy

* Data in NumPy to PyTorch tensor `torch.from_numpy(ndarray)`
* Data in PyTorch tensor to NumPy `torch.Tensor.numpy(ndaray)`

In [75]:
import torch
import numpy as np

array=np.arange(1.,8.)
tensor=torch.from_numpy(array)
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

When converting from numpy to pytorch it reflects the datatype of numpy which is float64 whereas as the default datatype of torch is float32

In [76]:
tensor=torch.ones(size=(3,3))
numpy_tensor=tensor.numpy()

In [77]:
tensor,numpy_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

##Reproducability
To reduce randomness we use **random seed**.

In [78]:
#creating 2 random tensors
random_tensor_A=torch.rand(4,5)
random_tensor_B=torch.rand(4,5)
random_tensor_A,random_tensor_B

(tensor([[0.9546, 0.6841, 0.4650, 0.6590, 0.7438],
         [0.4347, 0.2063, 0.8758, 0.2247, 0.8037],
         [0.9968, 0.1423, 0.9234, 0.4537, 0.2036],
         [0.3500, 0.0137, 0.6566, 0.7808, 0.6411]]),
 tensor([[0.8977, 0.3417, 0.3011, 0.7962, 0.6120],
         [0.0612, 0.0978, 0.2275, 0.7671, 0.0072],
         [0.4740, 0.0736, 0.0630, 0.6169, 0.9415],
         [0.1047, 0.2541, 0.1338, 0.0553, 0.3329]]))

In [79]:
print(random_tensor_A==random_tensor_B)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [80]:
#setting a random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(4,5)

torch.manual_seed(42)
random_tensor_D=torch.rand(4,5)

print(random_tensor_C==random_tensor_D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


Use `torch.manal_seed()` every time you use a torch function because it works for only one instance of torch

##Running tensors and PyTorch objects on the GPU's


###Getting a GPU

1. Use the google colab gpu's
2. Use your own GPU
3. Use cloud computing- GCP,AWS and AZURE

For 2,3 PyTorch+CUDA will need some setting up

In [81]:
##Checking for GPU
torch.cuda.is_available()

False

In [82]:
#Setup device agnostic code
device='cuda' if torch.cuda.is_available() else 'cpu' #if gpu is available set device to cuda or else make it cpu
device

'cpu'

In [83]:
torch.cuda.device_count() #counting the number of gpu's

0

###Putting Tensors to GPU's

In [84]:
#creating a tensor
tensor=torch.rand([4,5],device='cpu')
print(tensor,tensor.device)




tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]]) cpu


In [85]:
#move tensor to gpu
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]])

In [86]:
#if tensor is on gpu we cant convert it to numpy
tensor_on_gpu.numpy()

array([[0.26963168, 0.44136357, 0.29692084, 0.8316855 , 0.10531491],
       [0.26949483, 0.35881263, 0.19936377, 0.54719156, 0.00616044],
       [0.95155454, 0.07526588, 0.8860137 , 0.5832096 , 0.33764774],
       [0.808975  , 0.5779254 , 0.9039817 , 0.55465984, 0.3423134 ]],
      dtype=float32)

In [87]:
#to fix the above thing
tensor_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([[0.26963168, 0.44136357, 0.29692084, 0.8316855 , 0.10531491],
       [0.26949483, 0.35881263, 0.19936377, 0.54719156, 0.00616044],
       [0.95155454, 0.07526588, 0.8860137 , 0.5832096 , 0.33764774],
       [0.808975  , 0.5779254 , 0.9039817 , 0.55465984, 0.3423134 ]],
      dtype=float32)