#PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


##Introduction to tensors

###Creating tensors

In [2]:
#scalars
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#matrix
matrix=torch.tensor([[1,2],
                    [5,6]])
matrix

tensor([[1, 2],
        [5, 6]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
#tensor
tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
tensor.ndim

3

In [12]:
tensor.shape

torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
tensor[0][2][1]

tensor(8)

###Random Tensors

In [15]:
#creating a random tensor
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1295, 0.1298, 0.0200, 0.4638],
        [0.5661, 0.9343, 0.2862, 0.8969],
        [0.9325, 0.4054, 0.7958, 0.7209]])

In [16]:
random_tensor.ndim

2

In [18]:
random_tensor=torch.rand(1,3,5)
random_tensor

tensor([[[0.0819, 0.1307, 0.1962, 0.6612, 0.8116],
         [0.9316, 0.0664, 0.2365, 0.2501, 0.1471],
         [0.2639, 0.5669, 0.9407, 0.7946, 0.6692]]])

In [19]:
random_tensor.ndim,random_tensor.shape

(3, torch.Size([1, 3, 5]))

In [20]:
zero=torch.zeros(4,2,9)
zero

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [21]:
zero.dtype

torch.float32

In [22]:
ones=torch.ones(6,9)
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
#creating a tensor with range
range_tensor=torch.arange(start=0,end=1000,step=15)
range_tensor

tensor([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180, 195,
        210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405,
        420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570, 585, 600, 615,
        630, 645, 660, 675, 690, 705, 720, 735, 750, 765, 780, 795, 810, 825,
        840, 855, 870, 885, 900, 915, 930, 945, 960, 975, 990])

In [26]:
range_tensor.shape

torch.Size([67])

In [29]:
#to create tensors with similar shape to another tensor
zeros_like=torch.zeros_like(input=range_tensor)
print(zeros_like)
zeros_like.shape

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


torch.Size([67])

###Tensor Datatypes

In [30]:
float_16_tensor=torch.tensor([[9,8,7],
                              [6,7,8]],
                             dtype=torch.float16)
float_16_tensor

tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float16)

In [31]:
float_16_tensor.dtype

torch.float16

In [32]:
torch.tensor([1,2,3],
             dtype=None, #to edit the datatype of the tensor
             device=None, #what device the tensor is on
             requires_grad=False) #whether or not to track the gradients

tensor([1, 2, 3])

In [33]:
float_64_tensor=float_16_tensor.type(torch.float64)
float_64_tensor

tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float64)

In [34]:
float_16_tensor*float_64_tensor #dtype promotion

tensor([[81., 64., 49.],
        [36., 49., 64.]], dtype=torch.float64)

In [35]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_16_tensor*int_32_tensor #dtype promotion

tensor([[27., 48., 63.],
        [18., 42., 72.]], dtype=torch.float16)

###Getting attributes from tensor

1. Getting datatype- use tensor.dtype
2. Getting shape   - use tensor.shape
3. Getting device  - use tensor.device

In [42]:
tensor_random=torch.rand(3,4,7)
tensor_random

tensor([[[0.9527, 0.6856, 0.6824, 0.4584, 0.4428, 0.6119, 0.8753],
         [0.1595, 0.2185, 0.7317, 0.3652, 0.8757, 0.5342, 0.6291],
         [0.0486, 0.6743, 0.1186, 0.2637, 0.4989, 0.3249, 0.2264],
         [0.9072, 0.4369, 0.1154, 0.6404, 0.6756, 0.4533, 0.0276]],

        [[0.3691, 0.3529, 0.6043, 0.9768, 0.4788, 0.4283, 0.2710],
         [0.0338, 0.3944, 0.9938, 0.4120, 0.6295, 0.8792, 0.6181],
         [0.3259, 0.2297, 0.7491, 0.0980, 0.9517, 0.7851, 0.9422],
         [0.9765, 0.1198, 0.8712, 0.8164, 0.0212, 0.1284, 0.1068]],

        [[0.4090, 0.6178, 0.2198, 0.0891, 0.0270, 0.4784, 0.2942],
         [0.1728, 0.6361, 0.6427, 0.9667, 0.8726, 0.0265, 0.1409],
         [0.3696, 0.2202, 0.7580, 0.9911, 0.7692, 0.0785, 0.5117],
         [0.4259, 0.6996, 0.5664, 0.8696, 0.6203, 0.2368, 0.4716]]])

In [43]:
tensor_random.shape,tensor_random.dtype,tensor_random.device

(torch.Size([3, 4, 7]), torch.float32, device(type='cpu'))

In [44]:
int_32_tensor.shape,int_32_tensor.dtype,int_32_tensor.device

(torch.Size([3]), torch.int32, device(type='cpu'))

###Tensor Operations

1. Addition
2. Subtraction
3. Multiplication
4. division
5. Matrix Multiplication

In [46]:
#addition
tensor_random+10
#do the same operation for all values

tensor([[[10.9527, 10.6856, 10.6824, 10.4584, 10.4428, 10.6119, 10.8753],
         [10.1595, 10.2185, 10.7317, 10.3652, 10.8757, 10.5342, 10.6291],
         [10.0486, 10.6743, 10.1186, 10.2637, 10.4989, 10.3249, 10.2264],
         [10.9072, 10.4369, 10.1154, 10.6404, 10.6756, 10.4533, 10.0276]],

        [[10.3691, 10.3529, 10.6043, 10.9768, 10.4788, 10.4283, 10.2710],
         [10.0338, 10.3944, 10.9938, 10.4120, 10.6295, 10.8792, 10.6181],
         [10.3259, 10.2297, 10.7491, 10.0980, 10.9517, 10.7851, 10.9422],
         [10.9765, 10.1198, 10.8712, 10.8164, 10.0212, 10.1284, 10.1068]],

        [[10.4090, 10.6178, 10.2198, 10.0891, 10.0270, 10.4784, 10.2942],
         [10.1728, 10.6361, 10.6427, 10.9667, 10.8726, 10.0265, 10.1409],
         [10.3696, 10.2202, 10.7580, 10.9911, 10.7692, 10.0785, 10.5117],
         [10.4259, 10.6996, 10.5664, 10.8696, 10.6203, 10.2368, 10.4716]]])

In [47]:
#multiplication
tensor_random*21

tensor([[[20.0067, 14.3983, 14.3309,  9.6261,  9.2984, 12.8496, 18.3816],
         [ 3.3493,  4.5894, 15.3661,  7.6693, 18.3894, 11.2177, 13.2109],
         [ 1.0207, 14.1597,  2.4909,  5.5370, 10.4778,  6.8224,  4.7543],
         [19.0514,  9.1750,  2.4238, 13.4489, 14.1866,  9.5197,  0.5794]],

        [[ 7.7513,  7.4108, 12.6903, 20.5122, 10.0538,  8.9950,  5.6918],
         [ 0.7102,  8.2823, 20.8704,  8.6510, 13.2204, 18.4638, 12.9809],
         [ 6.8444,  4.8231, 15.7320,  2.0575, 19.9867, 16.4870, 19.7859],
         [20.5074,  2.5161, 18.2944, 17.1444,  0.4448,  2.6955,  2.2435]],

        [[ 8.5889, 12.9728,  4.6149,  1.8710,  0.5662, 10.0459,  6.1781],
         [ 3.6292, 13.3576, 13.4961, 20.3011, 18.3249,  0.5560,  2.9585],
         [ 7.7615,  4.6247, 15.9188, 20.8134, 16.1527,  1.6478, 10.7459],
         [ 8.9431, 14.6908, 11.8948, 18.2607, 13.0265,  4.9733,  9.9040]]])

In [51]:
#subtraction
tensor_random-9

tensor([[[-8.0473, -8.3144, -8.3176, -8.5416, -8.5572, -8.3881, -8.1247],
         [-8.8405, -8.7815, -8.2683, -8.6348, -8.1243, -8.4658, -8.3709],
         [-8.9514, -8.3257, -8.8814, -8.7363, -8.5011, -8.6751, -8.7736],
         [-8.0928, -8.5631, -8.8846, -8.3596, -8.3244, -8.5467, -8.9724]],

        [[-8.6309, -8.6471, -8.3957, -8.0232, -8.5212, -8.5717, -8.7290],
         [-8.9662, -8.6056, -8.0062, -8.5880, -8.3705, -8.1208, -8.3819],
         [-8.6741, -8.7703, -8.2509, -8.9020, -8.0483, -8.2149, -8.0578],
         [-8.0235, -8.8802, -8.1288, -8.1836, -8.9788, -8.8716, -8.8932]],

        [[-8.5910, -8.3822, -8.7802, -8.9109, -8.9730, -8.5216, -8.7058],
         [-8.8272, -8.3639, -8.3573, -8.0333, -8.1274, -8.9735, -8.8591],
         [-8.6304, -8.7798, -8.2420, -8.0089, -8.2308, -8.9215, -8.4883],
         [-8.5741, -8.3004, -8.4336, -8.1304, -8.3797, -8.7632, -8.5284]]])

In [52]:
#functions
tensor=torch.mul(tensor_random,10)
print(f"Multiplying 10 : {tensor}")
tensor=torch.add(tensor_random,10)
print(f"Adding 10 : {tensor}")

Multiplying 10 : tensor([[[9.5270, 6.8564, 6.8243, 4.5838, 4.4278, 6.1189, 8.7531],
         [1.5949, 2.1854, 7.3172, 3.6521, 8.7568, 5.3418, 6.2909],
         [0.4860, 6.7427, 1.1861, 2.6366, 4.9894, 3.2488, 2.2639],
         [9.0721, 4.3690, 1.1542, 6.4042, 6.7555, 4.5332, 0.2759]],

        [[3.6911, 3.5290, 6.0430, 9.7677, 4.7875, 4.2834, 2.7104],
         [0.3382, 3.9440, 9.9383, 4.1195, 6.2954, 8.7923, 6.1814],
         [3.2593, 2.2967, 7.4914, 0.9798, 9.5175, 7.8510, 9.4219],
         [9.7654, 1.1982, 8.7116, 8.1640, 0.2118, 1.2836, 1.0683]],

        [[4.0900, 6.1775, 2.1976, 0.8910, 0.2696, 4.7838, 2.9419],
         [1.7282, 6.3607, 6.4267, 9.6672, 8.7262, 0.2648, 1.4088],
         [3.6959, 2.2022, 7.5804, 9.9112, 7.6917, 0.7847, 5.1171],
         [4.2586, 6.9956, 5.6642, 8.6956, 6.2031, 2.3682, 4.7162]]])
Adding 10 : tensor([[[10.9527, 10.6856, 10.6824, 10.4584, 10.4428, 10.6119, 10.8753],
         [10.1595, 10.2185, 10.7317, 10.3652, 10.8757, 10.5342, 10.6291],
         [10.

####Matrix Multiplication

1. Element wise multiplication
2. Multiplying with another matrix i.e dot product

In [55]:
#Element wise multiplication
print(int_32_tensor)
print(float_16_tensor)
element_mul=int_32_tensor*float_16_tensor
element_mul

tensor([3, 6, 9], dtype=torch.int32)
tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float16)


tensor([[27., 48., 63.],
        [18., 42., 72.]], dtype=torch.float16)

In [56]:
#matrix multiplicationt
tensor_1=torch.rand(4,5)
tensor_2=torch.rand(5,4)

mat_mul=torch.matmul(tensor_1,tensor_2)
mat_mul_short=torch.mm(tensor_1,tensor_2)#alias of matmul
mat_mul_inv=torch.mm(tensor_2,tensor_1)

mat_mul,mat_mul_short,mat_mul_inv

(tensor([[0.6561, 0.5015, 1.1514, 0.9129],
         [1.3632, 0.7790, 1.4860, 1.6371],
         [0.7197, 0.4751, 1.0907, 0.9923],
         [0.7923, 0.6614, 1.0413, 0.7608]]),
 tensor([[0.6561, 0.5015, 1.1514, 0.9129],
         [1.3632, 0.7790, 1.4860, 1.6371],
         [0.7197, 0.4751, 1.0907, 0.9923],
         [0.7923, 0.6614, 1.0413, 0.7608]]),
 tensor([[0.1842, 0.6551, 1.0269, 0.3081, 1.1728],
         [0.2469, 0.5579, 0.5901, 0.3216, 0.6993],
         [0.5807, 1.0981, 0.9023, 0.6687, 1.0119],
         [0.2039, 0.5841, 0.8498, 0.3022, 0.9214],
         [0.3544, 0.9242, 1.1799, 0.4955, 1.3399]]))

In [57]:
#the most common error in matrix multiplication : shape error
tensor_mul_1=torch.rand(3,4)
tensor_mul_2=torch.rand(2,3)

mat_mul_tensor=torch.matmul(tensor_mul_1,tensor_mul_2) #the inner dimensions must match
mat_mul_tensor

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 2x3)

In [58]:
#using transpose
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
tensor_A.T,tensor_B.T

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [59]:
tensor_C=torch.mm(tensor_A,tensor_B.T)
tensor_C

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Tensor Aggregation
1. Mean
2. Max
3. Min
4. Sum

In [60]:
x=torch.arange(0,100,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [61]:
#min
torch.min(x)

tensor(0)

In [62]:
#max
torch.max(x)

tensor(95)

In [66]:
#mean
torch.mean(x)
#output shd match the tensor dtype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

torch.mean doesnt work with int types.

In [64]:
torch.mean(x.type(torch.float32))

tensor(47.5000)

In [65]:
#sum
torch.sum(x)

tensor(950)

###Positional min and max

In [67]:
#positional minimum
x.argmin()

tensor(0)

In [68]:
#positional maximum
x.argmax()

tensor(19)

In [69]:
x[0],x[19]

(tensor(0), tensor(95))

###Reshaping,stacking,squeezing and unsqueezing tensors

* Reshaping- reshaping the input tensor to a different tensor
* View     - return a view of an input tensor of certain shape but keep memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze  - remove dimensions from tensor
* Unsqueeze- add dimension to a tensor
* Permute  - return a view of the input with the dimensions permuted in a certain way

In [70]:
x=torch.arange(1.,50.,5)
x

tensor([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46.])

In [71]:
x.shape

torch.Size([10])

In [72]:
#reshaping
x_reshaped=x.reshape(5,2) #reshape has to be compatible with original shape
x_reshaped

tensor([[ 1.,  6.],
        [11., 16.],
        [21., 26.],
        [31., 36.],
        [41., 46.]])

In [73]:
#change the view
z=x.view(10,1)
z,z.shape

(tensor([[ 1.],
         [ 6.],
         [11.],
         [16.],
         [21.],
         [26.],
         [31.],
         [36.],
         [41.],
         [46.]]),
 torch.Size([10, 1]))

In [75]:
#changing z changes x because a view share the original tensor's memory
#like shallow copy ig
z[7,:]=52
z,x

(tensor([[ 1.],
         [ 6.],
         [11.],
         [16.],
         [21.],
         [26.],
         [31.],
         [52.],
         [41.],
         [46.]]),
 tensor([ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.]))

In [79]:
#stacking
x_stacked=torch.stack([x,x],dim=0)
x_stacked

tensor([[ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.],
        [ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.]])

In [77]:
x_stacked=torch.stack([x,x],dim=1)
x_stacked

tensor([[ 1.,  1.],
        [ 6.,  6.],
        [11., 11.],
        [16., 16.],
        [21., 21.],
        [26., 26.],
        [31., 31.],
        [52., 52.],
        [41., 41.],
        [46., 46.]])

In [81]:
#squeezing
x=torch.arange(0.,10.)
x_reshaped=x.reshape(1,10)

x_squeezed=torch.squeeze(x_reshaped,dim=0)

In [82]:
x_reshaped.shape,x_squeezed.shape

(torch.Size([1, 10]), torch.Size([10]))

In [83]:
#unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [84]:
#permuting-returns a view with dimensions rearranged
x=torch.ones(size=(4,2,7))
x


tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])

In [85]:
x_permuted=x.permute(2,0,1) #shifts axis 0->2, 1->0, 2->1


In [86]:
x_permuted.shape,x.shape

(torch.Size([7, 4, 2]), torch.Size([4, 2, 7]))

###Indexing in PyTorch

In [87]:
x=torch.arange(1.,10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [88]:
#indexing on the tensor
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [89]:
x[0][0],x[0,0]

(tensor([1., 2., 3.]), tensor([1., 2., 3.]))

In [90]:
x[0,1,1]

tensor(5.)

In [91]:
x[0,2,1]

tensor(8.)

In [95]:
#using : to select all values of a particular dimension
x[:,2]

tensor([[7., 8., 9.]])

In [96]:
x[:,2,:]

tensor([[7., 8., 9.]])

In [97]:
x[0,:,:]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

##PyTorch and NumPy

PyTorch has functionality to interact with NumPy

* Data in NumPy to PyTorch tensor `torch.from_numpy(ndarray)`
* Data in PyTorch tensor to NumPy `torch.Tensor.numpy(ndaray)`

In [105]:
import torch
import numpy as np

array=np.arange(1.,8.)
tensor=torch.from_numpy(array)
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

When converting from numpy to pytorch it reflects the datatype of numpy which is float64 whereas as the default datatype of torch is float32

In [99]:
tensor=torch.ones(size=(3,3))
numpy_tensor=tensor.numpy()

In [100]:
tensor,numpy_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

##Reproducability
To reduce randomness we use **random seed**.

In [103]:
#creating 2 random tensors
random_tensor_A=torch.rand(4,5)
random_tensor_B=torch.rand(4,5)
random_tensor_A,random_tensor_B

(tensor([[0.0721, 0.2052, 0.5677, 0.0144, 0.0107],
         [0.2448, 0.5118, 0.0137, 0.5892, 0.4475],
         [0.5343, 0.1657, 0.4083, 0.2733, 0.3168],
         [0.5955, 0.5832, 0.4874, 0.2824, 0.5124]]),
 tensor([[0.2191, 0.9798, 0.4012, 0.5044, 0.6466],
         [0.3628, 0.8393, 0.8155, 0.8310, 0.9694],
         [0.2611, 0.0628, 0.9383, 0.3078, 0.2064],
         [0.6250, 0.9850, 0.9178, 0.9405, 0.3456]]))

In [106]:
print(random_tensor_A==random_tensor_B)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [107]:
#setting a random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(4,5)

torch.manual_seed(42)
random_tensor_D=torch.rand(4,5)

print(random_tensor_C==random_tensor_D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


Use `torch.manal_seed()` every time you use a torch function because it works for only one instance of torch

##Running tensors and PyTorch objects on the GPU's


###Getting a GPU

1. Use the google colab gpu's
2. Use your own GPU
3. Use cloud computing- GCP,AWS and AZURE

For 2,3 PyTorch+CUDA will need some setting up

In [108]:
##Checking for GPU
torch.cuda.is_available()

True

In [109]:
#Setup device agnostic code
device='cuda' if torch.cuda.is_available() else 'cpu' #if gpu is available set device to cuda or else make it cpu
device

'cuda'

In [110]:
torch.cuda.device_count() #counting the number of gpu's

1

###Putting Tensors to GPU's

In [111]:
#creating a tensor
tensor=torch.rand([4,5],device='cpu')
print(tensor,tensor.device)




tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]]) cpu


In [112]:
#move tensor to gpu
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]], device='cuda:0')

In [113]:
#if tensor is on gpu we cant convert it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [114]:
#to fix the above thing
tensor_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([[0.26963168, 0.44136357, 0.29692084, 0.8316855 , 0.10531491],
       [0.26949483, 0.35881263, 0.19936377, 0.54719156, 0.00616044],
       [0.95155454, 0.07526588, 0.8860137 , 0.5832096 , 0.33764774],
       [0.808975  , 0.5779254 , 0.9039817 , 0.55465984, 0.3423134 ]],
      dtype=float32)